### ISSUE TITLE
[Bug?] Hidden terrain is not calculated

### ISSUE THREAD

**Issue by PalaNolho** [manuelVo/foundryvtt-terrain-ruler#13]
Not sure if it's an error to report here on on other modules but, when a terrain polygon is visible, if a token is dragged over it, the rule shows the correct multiplies values (based on the difficult terrain).

However, if the terrain is hidden, the ruler doesn't take it into account and doesn't apply the multiplier.

I want to be able to add difficult terrain but not show it to the players because the map already has a nice representation of the difficult terrains and it would be a shame for the players to have to see a bland dashed area instead of the cool map.

Maybe the difficult terrain could have a separate visible/invisible option that only control the visibility to players and another separate enabled/disabled option that controls if the terrain should or not be considered in the movement/ruler calculation?

**Note:** I'm using Enhanced Terrain Layer to place implement my difficult terrain
https://foundryvtt.com/packages/enhanced-terrain-layer

Thanks.

**Comment by manuelVo** [comment]
Enhanced Terrain Layer has two options to "hide" difficult terrain. There's the purple eye-button in the toolbar on the left that says "Enable/Disable Terrain". If that is turned off, the terrain won't be shown, but will still affect terrain calculation. Then there is the mystery-man button that says "Toggle Visibility State" that appears when you right click a terrain. That button actually disables the Terrain for the calculation (and hides it from the players). Those buttons are incorrectly labeled and I informed the Enhanced Terrain Layer author about this. It should be fixed in the next release of Enhanced Terrain Layer.

**Comment by PalaNolho** [comment]
it has been sorted, thanks
https://github.com/ironmonk88/enhanced-terrain-layer/issues/27
