### ISSUE TITLE
Support Euclidean Diagonal Rule

### ISSUE THREAD

**Issue by Teshynil** [manuelVo/foundryvtt-terrain-ruler#14]
I have the euclidean diagonal rule 7.07ft, but if i try to measure with the module active the diagonals it treats as equidistant 5/5/5
Terrain ruler version: 1.3.1
Enhanced Terrain Layer Version 1.0.29
Foundry version: 0.8.6
As a note, this is independent of measuring inside a terrain layer or outside
![image](https://user-images.githubusercontent.com/5714094/121825835-327c1080-cc7a-11eb-8886-a14ff1626b5f.png)

**Comment by manuelVo** [comment]
Euclidian as"Diagonal Movement Rule is currently unsupported for two reasons. One reason is a technical limitation, the other reason is because euclidian measurement as Diagonal Movement Rule is odd. I'll start explaining why it's odd, that way the technical limitation (which I will explain after that) will hopefully make more sense.

First let's start with equidistant and alternating. Those rules were designed with gridded play in mind. Equidistant is designed to be as simple as possible. Each square you move is 5ft. and that's it. It's as easy as it gets. Alternating is designed to be more realistic and approximates real (aka euclidean) measurements pretty well, while still being relatively simple to use.

Euclidean measurements on the other hand hasn't been designed for use with square. Instead it's designed to yield perfect results in gridless play. When using it in a gridded scene, the pixel perfect measurements are combined with forced snapping to a grid, which yields weird measurement artifacts. For example moving 3 squares diagonally costs 21ft. What if the character has only 20ft. speed? There are two options: First, the more fair rule is to round the result to the closest 5ft. increment. However this will yield the exact same results as the alternating rule, so you could just use that rule instead. Alternatively you could rule that a character cannot exceed their movement speed at all and the 20ft. character is only allowed to move 2 diagonals. This rule robs a character of 2.5ft. of movement each turn and as such is somewhat unfair and also looses any precision gains that using euclidean attempts to offer. As a result it never has an advantage opposed to the other grid rules. That's why it's odd.

Now for the technical reason. When euclidean measurements are used in gridless play, Terrain Ruler asks Enhanced Terrain Layer for the difficult terrain value of certain pixels on the screen to calculate a pixel perfect measurement including difficult terrain. However in gridded play, everyting snaps to a grid, and so do difficult terrain measurements. When playing with a grid, Terrain Ruler asks Enhanced Terrain Layer what difficult terrain cost applies to a given grid cell. Because of this in the following measurement the result would still be 7ft. even though it should be 14 ft. because of the difficult terrain. This is because both start and end cell of the measurement don't have their center in the difficult terrain and are determined to not be part of the difficult terrain as a result.
![grafik](https://user-images.githubusercontent.com/1705157/121969105-e614fb80-cd73-11eb-8e1c-fc8dfeaea5ae.png)

To be able to implement this it would be necessary for Enhanced Terrain Layer to offer a way to query the Difficult Terrain value for a screen pixel while a grid is enabled. This isn't currently possible and as such I'm unable to add this feature to Terrain Ruler. If you're interested in ever seeing this feature you should open an issue in their repository asking for addition of that feature.

However I strongly recommend trying out either gridless play (if you really like precise measurements) or the alternating rule (if you like gridded, but the equidistant rule is just too unrealistic) as a replacement of using euclidean measurements on a grid.

**Comment by Teshynil** [comment]
Thanks for the answer, i will take your recommendation of using alternating and opening a issue in their repository.

**Comment by manuelVo** [comment]
This is supported since 9198d1b (Terrain Ruler v1.4.0) thanks to work by @MAClavell
