### ISSUE TITLE
Dead Token Difficult Terrain Not Adding

### ISSUE THREAD

**Issue by Vaizt** [manuelVo/foundryvtt-terrain-ruler#29]
When dragging a token over a dead token difficult terrain is not calculated in the movement.

**Comment by manuelVo** [comment]
What type of grid are you using? Did you enable the setting in Enhanced Terran Layer that indicates that tokens should count as difficult terrain?

**Comment by Gawdl3y** [comment]
Mirroring my comment on ironmonk88/enhanced-terrain-layer#66

Experiencing the same issue - though the responsibility of this does seem most likely to lie with either Enhanced Terrain Layer or Terrain Ruler, here are the versions of all of the somewhat relevant software/modules that I'm using currently:
- Foundry 10.290
- Enhanced Terrain Layer 10.6
- Terrain Ruler 1.7.2
- Elevation Ruler 0.6.0
- Drag Ruler 1.13.2
- Drag Ruler D&D5e Integration 1.8.6

I have the settings enabled to count tokens as difficult terrain:
![image](https://user-images.githubusercontent.com/279900/202830097-46bd7b30-9f9a-4e43-92cb-eaca5b92fe36.png)

**Comment by manuelVo** [comment]
Counting tokens as difficult terrain is unsupported, as their shape is unclear on gridless. Should they occupy exactly the space that's taken up by their sprite? Or should they be approximated by the square that's drawn around the token? Or a circle? And if it's a circle, what size would the circle need to be?

I don't think there is one answer that most people could agree to. As a result, regardless of how this got implemented, many people would probably be dissatisfied with it. So we've opted to rather not support token terrain on gridless at all.

**Comment by Gawdl3y** [comment]
I think more people would be satisfied with an imperfect implementation than no support at all. To me, the implementation method seems obvious - just use the square that Foundry displays for the token, as you mentioned. That's automatically adjusted based on the creature size, and the little bit of extra space that results in around the sprite makes sense if you consider that any character likely is holding weapons and is capable of reaching/moving around within that space, rather than standing still like a statue.

It could also be put on a toggle (although it technically already is, in Enhanced Terrain Layer), so if somebody is dissatisfied with it entirely, they could just disable it. I think that having the option is better than not, because as it is right now, there is no possibility of it when using gridless scenes. If you turn out to be a madman 😛, and want to cover all possible desired behaviors, the mode could be selected from a dropdown list (Square, circle, sprite).
